# Generated by Django 3.1.4 on 2020-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='headnote',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
