# Generated by Django 3.1.4 on 2020-12-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20201211_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
