# Generated by Django 3.1.4 on 2020-12-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_faculty_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='language',
            field=models.CharField(choices=[('KG', 'Kyrgyz'), ('RU', 'Russian'), ('EN', 'English'), ('TU', 'Turkish')], default='Russian', max_length=2),
        ),
    ]
