# Generated by Django 3.1.4 on 2020-12-13 03:21

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_faculty_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='aid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=university.models.upload_img),
        ),
    ]
