# Generated by Django 3.1.4 on 2020-12-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_faculty_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaid',
            name='aid',
            field=models.BooleanField(default=True),
        ),
    ]
