# Generated by Django 3.1.4 on 2020-12-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_financeaid_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeaid',
            name='aid',
        ),
    ]
