# Generated by Django 3.1.4 on 2020-12-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_remove_financeaid_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeaid',
            name='title',
            field=models.CharField(default='Finance aid information', max_length=100),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Scholarship information', max_length=100)),
                ('description', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='university.university')),
            ],
        ),
    ]
